### ISSUE TITLE
Input string was not in a correct format 导致进程崩溃

### ISSUE THREAD

**Issue by LGinC** [whuanle/CZGL.SystemInfo#5]
nuget: `<PackageReference Include="CZGL.ProcessMetrics" Version="1.0.0" />`
runtime:    aspnet:5.0-alpine

Error:
Unhandled exception. System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.FormatException: Input string was not in a correct format.		
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
  at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at CZGL.ProcessMetrics.Counters.EventSourceCreatedListener.GetRelevantMetric(IDictionary`2 eventPayload)
   at CZGL.ProcessMetrics.Counters.EventSourceCreatedListener.OnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
--- End of inner exception stack trace ---

出现得很频繁,基本启动10分钟就挂了

目测是这里报错了
[https://github.com/whuanle/CZGL.SystemInfo/blob/e050a41b51f11e3dcba13aa01f57eeef03c6f33f/src/CZGL.ProcessMetrics/Counters/EventSourceCreatedListener.cs#L41](https://github.com/whuanle/CZGL.SystemInfo/blob/e050a41b51f11e3dcba13aa01f57eeef03c6f33f/src/CZGL.ProcessMetrics/Counters/EventSourceCreatedListener.cs#L41)

建议添加全局异常处理, 不让程序崩掉

**Comment by whuanle** [comment]
你好，已经修复了此问题，增加其它可靠性代码。
